### ISSUE TITLE
Cant switch logo color in Angular

### ISSUE THREAD

**Issue by boskiv** [algolia/docsearch#1695]
I'm trying to change a color for logo using flowbite CSS (tailwind)

Set variable to white
```
:root {
    --docsearch-logo-color: #fff;
}
```

But  nothing changes
![Screenshot 2022-12-05 at 22 25 24](https://user-images.githubusercontent.com/1939783/205736532-6fc56105-5ffe-4078-8614-7aec0d8936a8.png)

Can you suggest to me where I'm wrong?

**Comment by julien-deramond** [comment]
Observed the same thing while trying to use this same custom property. Sounds like a bug. Here is the workaround I've used if it can help someone :)

```css
.DocSearch-Logo svg .cls-1,
.DocSearch-Logo svg .cls-2 {
  fill: var(--docsearch-logo-color);
}
```

**Comment by CCKNBC** [comment]
```css
.DocSearch-Logo .cls-1,
.DocSearch-Logo .cls-2 {
    fill: var(--docsearch-logo-color) !important;
    color: var(--docsearch-logo-color) !important;
}
```
