### ISSUE TITLE
Uncaught (in promise) Error: [groupBy]: Object has no key lvl0

### ISSUE THREAD

**Issue by xiaoDC** [algolia/docsearch#186]
I use the default config , ajax get the result, but docsearch has a error. 
`Uncaught (in promise) Error: [groupBy]: Object has no key lvl0`
But I do not find the config about 'lv' in documents. Could you give me some config example? Thanks!

**Comment by vvo** [comment]
cc @maxiloc can you help?

**Comment by maxiloc** [comment]
Can you send the snippet of code you are using ?

**Comment by xiaoDC** [comment]
OK, the above is my config.

1. _config.yml
```
algolia:
  appId: "xxxxxxxxxxxxx"
  apiKey: "xxxxxxxxxxxxxx"
  adminApiKey: "xxxxxxxxxxxxx"
  chunkSize: 5000
  indexName: "xxxxxxxxxxx"
  fields:
    - title
    - content:strip
```

2. layout.swig
```
<!DOCTYPE html>
<html lang="{{ page.lang }}">
<head>
  {{ partial('partial/head') }}
</head>
<body>
  {{ partial('partial/header') }}
  <div id="container">
    {{ body }}
  </div>
</body>
<script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
<script type="text/javascript">
  docsearch({
    appId: '{{ config.algolia.appId }}',
    apiKey: '{{ config.algolia.apiKey }}',
    indexName: '{{ config.algolia.indexName }}',
    inputSelector: '#search-query',
    autocompleteOptions: {
      hint: false,
      autoselect: false
    }
  });
</script>
</html>

```
