### ISSUE TITLE
Make it easier to show search results *above* the input

### ISSUE THREAD

**Issue by pimterry** [algolia/docsearch#257]
Right now, in all conditions (as far as I can tell) the search results appear below the input. This is clearly awkward if your input is at the bottom of the page.

This is made more awkward by the CSS used for this being included inline in the dropdown element, making it hard to easily customize. I've worked around this ourselves with the following:

```css
	// Forcibly override the dropdown position
	.ds-dropdown-menu {
		top: initial !important;
		bottom: 100%;
	}

	// Remove the arrow/caret entirely, since it's awkward to fix
	.ds-dropdown-menu:before {
		display: none;
	}
```

It'd be nice to make this easier (in a perfect world, it'd happen automatically, the same as the left/right switch does), but it'd be good to at least document your recommended approach to this somewhere.
